# Generated by Django 5.2.16 on 2026-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('emergency', 'Emergency limited access'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20),
        ),
    ]
