# Generated by Django 5.2.16 on 2026-08-01 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0005_emergencyaccessinvitation_caseaccessgrant_and_more'),
        ('locations', '0003_hotspot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('case', 'Case alert'), ('hotspot', 'Hotspot alert'), ('route', 'Route alert'), ('emergency_access', 'Emergency access alert'), ('system', 'System alert'), ('manual', 'Manual alert')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(help_text='Use anonymized information only. Do not include names, phone numbers, NID numbers, or exact private addresses.')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='Roles that should receive this alert. An empty list means explicitly selected users only.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='locations.hotspot')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='locations.route')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='delivered', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_records', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_aler_severit_12d0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'status'], name='alerts_aler_alert_t_82e8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['expires_at', 'status'], name='alerts_aler_expires_d16f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['user', 'is_read'], name='alerts_aler_user_id_1a9bba_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['user', 'is_acknowledged'], name='alerts_aler_user_id_7b911d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrecipient',
            index=models.Index(fields=['delivery_status', 'created_at'], name='alerts_aler_deliver_42e838_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrecipient',
            constraint=models.UniqueConstraint(fields=('alert', 'user'), name='unique_alert_recipient'),
        ),
    ]
