# Generated by Django 5.2.16 on 2026-08-01 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('executive_summary', 'Executive summary'), ('case_analysis', 'Case analysis'), ('geographic_risk', 'Geographic risk analysis'), ('route_analysis', 'Route analysis'), ('alert_analysis', 'Alert analysis'), ('audit_compliance', 'Audit and compliance')], max_length=30)),
                ('output_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('pdf', 'PDF')], default='json', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Non-sensitive filters used to generate the report.')),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Aggregated statistics generated for the report.')),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['generated_by', 'created_at'], name='reports_rep_generat_b60f00_idx'), models.Index(fields=['date_from', 'date_to'], name='reports_rep_date_fr_12c9d5_idx')],
            },
        ),
    ]
