# Generated by Django 5.2.16 on 2026-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('division', models.CharField(choices=[('barishal', 'Barishal'), ('chattogram', 'Chattogram'), ('dhaka', 'Dhaka'), ('khulna', 'Khulna'), ('mymensingh', 'Mymensingh'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('sylhet', 'Sylhet')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['division', 'name'], name='locations_d_divisio_7111d2_idx'), models.Index(fields=['is_active'], name='locations_d_is_acti_dfb202_idx')],
            },
        ),
    ]
