# Generated by Django 5.2.16 on 2026-07-29 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('route_type', models.CharField(choices=[('domestic', 'Domestic'), ('cross_border', 'Cross-border')], default='domestic', max_length=20)),
                ('transport_mode', models.CharField(choices=[('road', 'Road'), ('rail', 'Rail'), ('water', 'Water'), ('air', 'Air'), ('mixed', 'Mixed')], default='road', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('evidence_summary', models.TextField(blank=True, help_text='Use anonymized or synthetic information only.')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_routes', to='locations.district')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_routes', to='locations.district')),
            ],
            options={
                'ordering': ('-updated_at', 'name'),
                'indexes': [models.Index(fields=['origin', 'destination'], name='locations_r_origin__f09425_idx'), models.Index(fields=['risk_level', 'is_active'], name='locations_r_risk_le_04bbb8_idx'), models.Index(fields=['route_type', 'is_active'], name='locations_r_route_t_e92243_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='route_origin_destination_different')],
            },
        ),
    ]
