# Generated by Django 5.2.16 on 2026-07-29 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('hotspot_type', models.CharField(choices=[('transit_hub', 'Transit hub'), ('border_area', 'Border area'), ('urban_center', 'Urban center'), ('industrial_area', 'Industrial area'), ('coastal_area', 'Coastal area'), ('other', 'Other')], default='other', max_length=30)),
                ('recent_case_count', models.PositiveIntegerField(default=0, help_text='Number of relevant cases in the configured recent period.')),
                ('active_route_count', models.PositiveIntegerField(default=0)),
                ('verified_route_count', models.PositiveIntegerField(default=0)),
                ('vulnerability_score', models.PositiveSmallIntegerField(default=0, help_text='Context score from 0 to 100 using approved criteria.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=dict, help_text='Transparent factor values and weights used in scoring.')),
                ('risk_explanation', models.TextField(blank=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hotspots', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotspots', to='locations.district')),
            ],
            options={
                'ordering': ('-risk_score', 'name'),
                'indexes': [models.Index(fields=['district', 'is_active'], name='locations_h_distric_40c871_idx'), models.Index(fields=['risk_level', 'is_active'], name='locations_h_risk_le_640c16_idx'), models.Index(fields=['hotspot_type', 'is_active'], name='locations_h_hotspot_8b28ea_idx')],
            },
        ),
    ]
