# Generated by Django 5.2.16 on 2026-07-29 18:34

import cases.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_hotspot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(default=cases.models.generate_case_reference, editable=False, max_length=25, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Use anonymized information only. Do not include names, phone numbers, NID numbers, or exact addresses.')),
                ('category', models.CharField(choices=[('suspected', 'Suspected trafficking'), ('confirmed', 'Confirmed trafficking'), ('rescue', 'Rescue operation'), ('route_intelligence', 'Route intelligence'), ('other', 'Other')], default='suspected', max_length=30)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('investigating', 'Investigating'), ('action_required', 'Action required'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('confidentiality', models.CharField(choices=[('internal', 'Internal'), ('restricted', 'Restricted'), ('highly_restricted', 'Highly restricted')], default='restricted', max_length=30)),
                ('location_description', models.CharField(blank=True, help_text='Use a general location description, not an exact address.', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('total_victims', models.PositiveIntegerField(default=0)),
                ('minor_victims', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('incident_district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='locations.district')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reported_at', 'reference_code'),
                'indexes': [models.Index(fields=['status', 'priority'], name='cases_case_status_7ed306_idx'), models.Index(fields=['incident_district', 'status'], name='cases_case_inciden_086f6f_idx'), models.Index(fields=['assigned_to', 'status'], name='cases_case_assigne_e88b3b_idx'), models.Index(fields=['category', 'is_verified'], name='cases_case_categor_700043_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('minor_victims__lte', models.F('total_victims'))), name='case_minors_not_more_than_total')],
            },
        ),
    ]
