# Generated by Django 5.2.16 on 2026-07-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('status_change', 'Status change'), ('note', 'Investigation note'), ('assignment', 'Assignment change'), ('verification', 'Verification change'), ('other', 'Other')], default='note', max_length=30)),
                ('previous_status', models.CharField(blank=True, choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('investigating', 'Investigating'), ('action_required', 'Action required'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=30)),
                ('new_status', models.CharField(blank=True, choices=[('reported', 'Reported'), ('under_review', 'Under review'), ('investigating', 'Investigating'), ('action_required', 'Action required'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=30)),
                ('note', models.TextField(help_text='Use anonymized information only. Do not include identifying victim information.')),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['case', 'created_at'], name='cases_caseu_case_id_6f7640_idx'), models.Index(fields=['update_type', 'created_at'], name='cases_caseu_update__789c56_idx')],
            },
        ),
    ]
