# Generated by Django 5.2.16 on 2026-07-29 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseupdate'),
        ('locations', '0003_hotspot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('suspected', 'Suspected connection'), ('confirmed', 'Confirmed connection'), ('origin', 'Origin point'), ('transit', 'Transit point'), ('destination', 'Destination point')], default='suspected', max_length=20)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('evidence_note', models.TextField(blank=True, help_text='Use anonymized evidence only. Do not include personal identifiers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_links', to='cases.case')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_route_links', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_links', to='locations.route')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['case', 'relationship_type'], name='cases_caser_case_id_1d4cad_idx'), models.Index(fields=['route', 'confidence_level'], name='cases_caser_route_i_a4fe30_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'route'), name='unique_case_route_link')],
            },
        ),
    ]
