# Generated by Django 5.2.16 on 2026-07-29 18:39

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VictimProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_code', models.CharField(default=cases.models.generate_victim_code, editable=False, max_length=20, unique=True)),
                ('age_group', models.CharField(choices=[('child', 'Child (0–11)'), ('adolescent', 'Adolescent (12–17)'), ('adult', 'Adult (18+)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('exploitation_type', models.CharField(choices=[('labour', 'Forced labour'), ('sexual', 'Sexual exploitation'), ('forced_marriage', 'Forced marriage'), ('domestic_servitude', 'Domestic servitude'), ('organ_removal', 'Organ removal'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('support_status', models.CharField(choices=[('identified', 'Identified'), ('rescued', 'Rescued'), ('referred', 'Referred for support'), ('receiving_support', 'Receiving support'), ('reintegrating', 'Reintegrating'), ('unknown', 'Unknown')], default='identified', max_length=30)),
                ('country_of_origin', models.CharField(blank=True, help_text='Country-level information only; do not enter an exact address.', max_length=100)),
                ('support_needs', models.JSONField(blank=True, default=list, help_text='Use general categories such as medical, legal, shelter, counselling, or family support.')),
                ('protected_note', models.TextField(blank=True, help_text='Do not include names, contact details, ID numbers, photos, or exact addresses.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim_profiles', to='cases.case')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_victim_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('anonymous_code',),
                'indexes': [models.Index(fields=['case', 'support_status'], name='cases_victi_case_id_586908_idx'), models.Index(fields=['age_group', 'exploitation_type'], name='cases_victi_age_gro_702212_idx')],
            },
        ),
    ]
