# Generated by Django 5.2.16 on 2026-07-30 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_victimprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAccessInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('reason', models.CharField(help_text='Give a brief operational reason without including victim-identifying information.', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_emergency_invitations', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_invitations', to='cases.case')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_emergency_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('limited', 'Limited case access'), ('operational', 'Operational case access')], default='limited', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='cases.case')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_case_access', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_case_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_access_grants', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='access_grant', to='cases.emergencyaccessinvitation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='emergencyaccessinvitation',
            index=models.Index(fields=['invitee_email', 'status'], name='cases_emerg_invitee_18f1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyaccessinvitation',
            index=models.Index(fields=['case', 'status'], name='cases_emerg_case_id_60dfc7_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyaccessinvitation',
            index=models.Index(fields=['expires_at', 'status'], name='cases_emerg_expires_9c4051_idx'),
        ),
        migrations.AddIndex(
            model_name='caseaccessgrant',
            index=models.Index(fields=['user', 'is_active'], name='cases_casea_user_id_7d7e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='caseaccessgrant',
            index=models.Index(fields=['case', 'is_active'], name='cases_casea_case_id_16b8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='caseaccessgrant',
            index=models.Index(fields=['expires_at', 'is_active'], name='cases_casea_expires_e039ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='caseaccessgrant',
            constraint=models.UniqueConstraint(fields=('case', 'user'), name='unique_case_access_grant'),
        ),
    ]
