# Generated by Django 5.2.16 on 2026-08-01 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, help_text='Email snapshot retained if the user is later deleted.', max_length=254)),
                ('action', models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('create', 'Create'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('approve_user', 'Approve user'), ('reject_user', 'Reject user'), ('emergency_invite', 'Emergency invitation created'), ('emergency_access', 'Emergency access accepted'), ('emergency_revoke', 'Emergency access revoked'), ('alert_read', 'Alert marked as read'), ('alert_acknowledge', 'Alert acknowledged')], max_length=40)),
                ('resource_type', models.CharField(blank=True, help_text='Example: case, route, hotspot, alert, or user.', max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('resource_label', models.CharField(blank=True, help_text='Safe, non-sensitive resource description.', max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store only safe metadata. Never store passwords, tokens, or confidential case details.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['resource_type', 'resource_id', 'created_at'], name='audit_audit_resourc_aa1fd0_idx'), models.Index(fields=['success', 'created_at'], name='audit_audit_success_0a1eab_idx')],
            },
        ),
    ]
